#!/usr/bin/env bash
#this while loop will display 'Best School' 9 times in the shell, but on the 9th time, you'd get a greeting

x=1

while [ $x -lt 10 ]
do
    if [ $x -eq 9 ]
    then
    echo "Hi"
    fi
    echo "Best School"
    (( x++ ))
done