#!/usr/bin/env bash
#this while loop will displays bad luck for the 4th loop iteration, displays bad luck from Japan for the 8th loop iteration and displays Best School for the other iterations
x=1

while [ $x -le 20 ]
do  
    echo $x

    case $x

    in
    4)echo "bad luck from China";;
    9)echo "bad luck from Japan";;
    17)echo "bad luck from Italy";;

    esac
    (( x++ ))
done